[package]
name = "nitro-da-indexer-api"
description = "The shared API for the Solana Indexer."
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
publish = { workspace = true }

[dependencies]
# External dependencies from crates.io
jsonrpsee = { workspace = true, features = ["client-core"] }
serde = { workspace = true, features = ["alloc", "derive"] }

# Solana & Agave
anchor-lang = { workspace = true }
solana-sdk = { workspace = true }

# Locals
blober = { workspace = true }
nitro-da-proofs = { workspace = true }
