[workspace]
resolver = "2"
members = [
  "crates/cli",
  "crates/client",
  "crates/indexer",
  "crates/indexer-api",
  "crates/proofs",
]
exclude = ["programs"]

[workspace.package]
edition = "2024"
version = "0.1.4"
license = "MIT OR Apache-2.0"
authors = ["Nitro Labs <team@nitro.technology>"]
homepage = "https://www.termina.technology"
publish = true
repository = "https://github.com/nitro-svm/nitro-data-module"

[workspace.dependencies]
# External dependencies
anyhow = "1.0.95"
arbitrary = { version = "1.4.1", features = ["derive"] }
arbtest = "0.3.2"
async-channel = "2.3.1"
async-trait = "0.1.83"
bincode = "1.3.3"
blake3 = { version = "1.5.5", default-features = false }
bon = "3.5.1"
bytesize = "1.3.0"
chrono = "0.4.39"
clap = { version = "4.5.29", features = ["derive", "env"] }
crossbeam = "0.8.4"
csv = "1.3.1"
futures = { version = "0.3.31", default-features = false }
gadgets-scfs = { git = "https://github.com/nitro-svm/solana-gadgets", rev = "66edbad4ed4e2085f5967cd57541d7f4f6b50bcb" }
hex = { version = "0.4.3", default-features = false }
itertools = "0.14.0"
jsonrpsee = { version = "0.24.7", features = ["macros", "server-core"] }
mutants = "0.0.3"
native_db = "0.8.1"
# Has to be 0.4.20 for native_db compatibility
native_model = "0.4.20"
# Has to be 0.7 for Solana SDK compatibility
rand = "0.7"
risc0-zkvm = { version = "1.2.0", default-features = false }
schemars = "0.8.21"
serde_json = { version = "1.0.134", default-features = false }
serde = { version = "1.0.216", default-features = false }
tempfile = "3.14.0"
thiserror = "2.0.9"
tokio = { version = "1.42.0", features = ["full"] }
tokio-util = "0.7.13"
tracing-subscriber = "0.3.19"
tracing = { version = "0.1.41", default-features = false }
walkdir = "2.5.0"

# Solana & Agave
agave-geyser-plugin-interface = "=2.1.0"
solana-accounts-db = "=2.1.0"
solana-bpf-loader-program = "=2.1.0"
solana-cli = "=2.1.0"
solana-cli-config = "=2.1.0"
solana-client = "=2.1.0"
solana-compute-budget = "=2.1.0"
solana-program = "=2.1.0"
solana-program-runtime = "=2.1.0"
solana-rpc-client = "=2.1.0"
solana-rpc-client-api = "=2.1.0"
solana-sdk = "=2.1.0"
solana-test-validator = "=2.1.0"
solana-transaction-status = "=2.1.0"
solana_rbpf = "=0.8.4"
anchor-lang = "=0.31.1"

# Nitro
svm-engine-keys = "0.1.0-alpha"

# Locals
nitro-da-cli = "0.1.4"
nitro-da-client = "0.1.4"
nitro-da-indexer = { path = "crates/indexer" }
nitro-da-indexer-api = "0.1.4"
nitro-da-proofs = "0.1.4"
nitro-da-blober = { version = "0.1.5", features = ["no-entrypoint"] }

[patch.crates-io]
nitro-da-cli = { path = "crates/cli" }
nitro-da-client = { path = "crates/client" }
nitro-da-indexer-api = { path = "crates/indexer-api" }
nitro-da-proofs = { path = "crates/proofs" }
nitro-da-blober = { path = "programs/programs/blober" }
