error_values = [
    "crate::accounts_delta_hash::exclusion::left::ExclusionLeftProofError::InclusionProofNotForLeftmost",
    "crate::accounts_delta_hash::exclusion::inner::ExclusionInnerProofError::PathLengthMismatch",
    "crate::accounts_delta_hash::exclusion::right::ExclusionRightProofError::InclusionProofNotForRightmost",
    "crate::accounts_delta_hash::exclusion::empty::ExclusionEmptyProofError::RootMismatch",
    "crate::accounts_delta_hash::exclusion::ExclusionProofError::Empty(crate::ExclusionEmptyProofError::RootMismatch)",
    "crate::hasher_account_state::HasherAccountStateError::SlotMismatch { expected: 0, found: 1 }",
    "crate::compound::completeness::CompoundCompletenessProofError::ExcludedAccountNotHasher",
    "crate::compound::inclusion::CompoundInclusionProofError::InvalidNumberOfBlobs",
    "crate::vote::multi::MultiVoteError::NotEnoughTrustedVoters { required_votes: 0, number_of_trusted_votes: 0 }",
    "crate::vote::single::SingleVoteError::NoSlotHashes",
]
