[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
data-anchor-blober = "anchorE4RzhiFx3TEFep6yRNK9igZBzMVWziqjbGHp2"
data-anchor-data-correctness-verifier = "oGbL1FPtd7Uix2cwjViMiUciz7UJ2U3gqnxZypXsXQi"
data-anchor-dawn-sla-verifier = "A4Ks3ivLsBVvysaf6BMTNjdcvig1Ti8cSkoMBqYDdsGF"

[programs.localnet]
data-anchor-blober = "anchorE4RzhiFx3TEFep6yRNK9igZBzMVWziqjbGHp2"
data-anchor-data-correctness-verifier = "oGbL1FPtd7Uix2cwjViMiUciz7UJ2U3gqnxZypXsXQi"
data-anchor-dawn-sla-verifier = "A4Ks3ivLsBVvysaf6BMTNjdcvig1Ti8cSkoMBqYDdsGF"

[programs.mainnet]
data-anchor-blober = "anchorE4RzhiFx3TEFep6yRNK9igZBzMVWziqjbGHp2"
data-anchor-data-correctness-verifier = "oGbL1FPtd7Uix2cwjViMiUciz7UJ2U3gqnxZypXsXQi"
data-anchor-dawn-sla-verifier = "A4Ks3ivLsBVvysaf6BMTNjdcvig1Ti8cSkoMBqYDdsGF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
