[toolchain]
anchor_version = "0.30.1-db6da5c67d896e0a94c158f69e9b235e364b3064"

[features]
resolution = true
skip-lint = false

[programs.localnet]
blober = "CdczmTavZ6HQwSvEgKJtyrQzKYV4MyU6EZ4Gz5KsULoP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
