name: Release and Generate Public URLs

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release-and-upload:
    name: Build, Upload, and Generate URLs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build Binary
        run: |
          cargo build --release --target ${{ matrix.target }} -p nitro-da-cli

      - name: Prepare Artifact
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          tar -czvf ../../../nitro-da-cli-${{ github.ref_name }}-${{ matrix.target }}.tar.gz nitro-da-cli

      - name: Upload to AWS S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: "."
          DEST_DIR: "nitro-da-cli/${{ github.ref_name }}"
